name: Selenium Tests

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch: # Allows manual trigger from GitHub Actions

jobs:
  test:
    runs-on: windows-latest  # Runs on Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Fetch the latest code
      
      - name: Setup Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Temurin JDK
          java-version: '17'  # Change version if needed

      - name: Setup Chrome & ChromeDriver
        uses: browser-actions/setup-chrome@latest  # Installs Chrome
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2  # Installs ChromeDriver
        with:
          chromedriver-version: latest

      - name: Run Selenium Tests
        run: mvn clean test  # Runs your tests with Maven
