name: Run Selenium Tests Every 5 Hours on Windows

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: windows-latest  # Use Windows Runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change to your Java version

      - name: Install Google Chrome
        run: choco install googlechrome -y  # Install Chrome using Chocolatey

      - name: Install ChromeDriver
        run: choco install chromedriver -y  # Install matching ChromeDriver

      - name: Verify Chrome and ChromeDriver Versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Install Maven Dependencies
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test
