name: Run Selenium Tests Every 5 Hours

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch:  # Allows manual trigger from GitHub

jobs:
  test:
    runs-on: ubuntu-latest  # Uses a Linux runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch latest code

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change to your Java version

      - name: Set Up Chrome Driver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'

      - name: Install Maven Dependencies
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test
